//! Regenerates src/inter_metrics.rs from an installed Inter collection (make mermaid-metrics):
//!   cargo run --example gen_metrics -- /usr/share/fonts/inter/Inter.ttc > src/inter_metrics.rs
//! It looks the faces up by name ("Inter Regular", "Inter Bold"), so any Inter 4.x collection works.
use std::fmt::Write;

fn face_index(data: &[u8], want: &str) -> u32 {
    let n = ttf_parser::fonts_in_collection(data).unwrap_or(1);
    for i in 0..n {
        let f = ttf_parser::Face::parse(data, i).unwrap();
        let name = f
            .names()
            .into_iter()
            .find(|n| n.name_id == ttf_parser::name_id::FULL_NAME && n.is_unicode())
            .and_then(|n| n.to_string())
            .unwrap_or_default();
        if name == want {
            return i;
        }
    }
    panic!("face {want:?} not found");
}

fn main() {
    let path = std::env::args().nth(1).expect("path to Inter.ttc");
    let data = std::fs::read(&path).unwrap();
    let regular = ttf_parser::Face::parse(&data, face_index(&data, "Inter Regular")).unwrap();
    let bold = ttf_parser::Face::parse(&data, face_index(&data, "Inter Bold")).unwrap();
    assert_eq!(regular.units_per_em(), bold.units_per_em());
    let mut rows = String::new();
    let mut count = 0;
    for cp in 0x20u32..0x3000 {
        let Some(ch) = char::from_u32(cp) else { continue };
        let (Some(gr), Some(gb)) = (regular.glyph_index(ch), bold.glyph_index(ch)) else { continue };
        let (Some(ar), Some(ab)) = (regular.glyph_hor_advance(gr), bold.glyph_hor_advance(gb)) else { continue };
        writeln!(rows, "    (0x{cp:04X}, {ar}, {ab}),").unwrap();
        count += 1;
    }
    println!("// Code generated by examples/gen_metrics.rs from {}; DO NOT EDIT.", path.rsplit('/').next().unwrap());
    println!("// Horizontal advances of Inter Regular and Inter Bold (SIL OFL 1.1), in font units.");
    println!();
    println!("pub const UNITS_PER_EM: f64 = {}.0;", regular.units_per_em());
    println!();
    println!("/// (codepoint, regular advance, bold advance), sorted by codepoint; {count} entries.");
    println!("pub static ADVANCES: &[(u16, u16, u16)] = &[");
    print!("{rows}");
    println!("];");
}
